# .github/workflows/k8s-deploy.yml
name: 🚀 Kubernetes Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - staging
          - production
      image-tag:
        required: true
        type: string
      k8s-manifests:
        required: false
        type: string
        default: k8s/

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure K8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ inputs.k8s-manifests }}
          kubectl rollout status deployment/app-deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}