# .github/workflows/secure-container.yml
name: 🛡️ Secure Container Build & Sign

on:
  workflow_call:  # Make reusable
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: false
        type: string
        default: .

env:
  REGISTRY: ghcr.io

jobs:
  build-and-sign:
    name: Build, Scan & Sign
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Image Tag
        id: image_tag
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG=${{ env.REGISTRY }}/$REPO_NAME/${{ inputs.image-name }}:${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-context }}
          push: true
          tags: ${{ steps.image_tag.outputs.IMAGE_TAG }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🚨 Trivy Security Scan
        id: trivy-scan
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ steps.image_tag.outputs.IMAGE_TAG }}
          exit-code: 1
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: ✍️ Sign Container Image
        if: steps.trivy-scan.outcome == 'success'
        run: |
          cosign sign --yes ${{ steps.image_tag.outputs.IMAGE_TAG }}